DROP TABLE IF EXISTS answer;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS question_tag;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS choice;
DROP TABLE IF EXISTS question;

CREATE TABLE question (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	question TEXT NOT NULL,
	helptext TEXT,
	cardinality BIT NOT NULL,
	created DATETIME NOT NULL DEFAULT NOW(),
	deleted DATETIME
);

CREATE TABLE choice (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	question_id INT NOT NULL 
	choice TEXT NOT NULL,
	score INT NOT NULL,
	created DATETIME NOT NULL DEFAULT NOW(),
	deleted DATETIME,
	FOREIGN KEY (question_id) REFERENCES question(id)
);

CREATE TABLE tag (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(15),
	created DATETIME NOT NULL DEFAULT NOW(),
	deleted DATETIME
);

CREATE TABLE question_tag (
	question_id INT NOT NULL,
	tag_id INT NOT NULL,
	PRIMARY KEY (question_id, tag_id)
);

CREATE TABLE person (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE answer (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	person_id INT NOT NULL,
	question_id INT NOT NULL,
	choice_id INT NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);